version: "3"
services:
  web:
    image: php7-alpine
    environment:
      - void
    ports:
      - "8080:8080"
    volumes:
      - ./:/srv/http
    command: "php artisan serve --host=0.0.0.0 --port=8080"
    working_dir: /srv/http
    links:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: remazing_cc
    ports:
      - "5433:5432"
    expose:
      - "5433"
